### ISSUE TITLE
1-char and 2-char

### ISSUE THREAD

**Issue by moso** [jomo/tld_checker#2]
Hey,

Nice tool, however, it will report a domain available eventhough the NIC has a rule of, eg, 3 characters as minimum. Does IANA have a similar list or info about which TLDs will block registration of 1-char and 2-char domain names? If so, it would be cool to have it built into this tool.

Thanks!

**Comment by jomo** [comment]
To my knowledge, this is not any sort of technical limitation but rather just a policy that every registry defines with their own words.
